In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Task 1:

std_data = {
    "Name" : ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]
}

ds=pd.DataFrame(std_data)
ds

In [ ]:
marks = ds["Marks"]

#Average marks:
print("Average of Marks is: ")
print(marks.mean())

#Maximum marks:
print("Maximum value in Marks is: ")
print(marks.max())

#Minimum marks:
print("Minimum value in Marks is: ")
print(marks.min())

students = ds["Name"]
#Total Students:
print("Total Number of students are: ")
print(students.count())

Average of Marks is:
71.0
Maximum value in Marks is:
95
Minimum value in Marks is:
45
Total Number of students are:
5

In [ ]:
#Task 2:
passed_students = ds[ds["Marks"]>=50]
print("Passed Students are: ")
print(passed_students)

failed_students = ds[ds["Marks"]<=50]
print("Failed Students are: ")
print(failed_students)

In [ ]:
#Task 3:

from numpy import dsplit
ds["City"] = ["Karachi", "Lahore", "Islamabad", "Hyderabad", "Nawabshah"]
# display data with only karachi city
ds[ds["City"] == "Karachi"]

In [ ]:
#Task 4:
std_info = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"],
    "Marks": [70, 85, 60, 95, 45]
}

ds = pd.DataFrame(std_info)
ds

     Name Courses  Marks
0     Ali      AI     70
1    Sara     Web     85
2   Ahmed      AI     60
3  Ayesha     Web     95
4    Zain      AI     45

In [ ]:
# Average Marks of each course

Avg_marks = ds.groupby("Courses")["Marks"].mean()
print("Average Marks of each course are: ")

print(Avg_marks)

Average Marks of each course are:
Courses
AI     58.333333
Web    90.000000
Name: Marks, dtype: float64

In [ ]:
#Task 5:
Data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"],
    "Roll_No" : [41456, 42678, 43256, 47653, 45980],
    "Marks": [70, None, 60, None, 45]

}

ds = pd.DataFrame(Data)
ds

     Name Courses  Roll_No  Marks
0     Ali      AI    41456   70.0
1    Sara     Web    42678    NaN
2   Ahmed      AI    43256   60.0
3  Ayesha     Web    47653    NaN
4    Zain      AI    45980   45.0

In [ ]:
print(ds.isnull().sum())

Name       0
Courses    0
Roll_No    0
Marks      2
dtype: int64

In [ ]:
ds['Marks'] = ds['Marks'].fillna(ds['Marks'].mean())
ds

     Name Courses  Roll_No      Marks
0     Ali      AI    41456  70.000000
1    Sara     Web    42678  58.333333
2   Ahmed      AI    43256  60.000000
3  Ayesha     Web    47653  58.333333
4    Zain      AI    45980  45.000000

In [ ]:
ds1 = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks": [70, 85, 60, 95, 45]

}

ds2 = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Courses": ["AI", "Web", "AI", "Web", "AI"],
    "Roll_no": [456, 789, 908, 678, 567]
}

ds1 = pd.DataFrame(ds1)
ds2 = pd.DataFrame(ds2)

final_ds = pd.merge(ds1 , ds2, on = "Name")
print(final_ds)

     Name  Marks Courses  Roll_no
0     Ali     70      AI      456
1    Sara     85     Web      789
2   Ahmed     60      AI      908
3  Ayesha     95     Web      678
4    Zain     45      AI      567